apiVersion: v1
kind: Service
metadata:
  name: ai-assistant-api-service
  labels:
    app: ai-assistant-api
spec:
  selector:
    app: ai-assistant-api
  ports:
    - name: ai-service-port
      protocol: TCP
      port: 8003
      targetPort: 8003
