# Default values for ai-assistant-api.
replicaCount: 1

image:
  repository: ghcr.io/prospjx/ai-assistant-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: "ai-assistant-api"

strategy:
  type: RollingUpdate

service:
  type: ClusterIP
  port: 8003

existingSecret: "ai-assistant-api-secret"

env:
  host: "0.0.0.0"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
