name: AI Assitant CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Lint Code
        run: ruff check .

      - name: Format Code
        run: black --check .

      - name: Run Tests
        run: pytest

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/prospjx/ai-assistant-api:v${{ github.run_number }} -t ghcr.io/prospjx/ai-assistant-api:latest .

      - name: Push to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/prospjx/ai-assistant-api:v${{ github.run_number }}
          docker push ghcr.io/prospjx/ai-assistant-api:latest
